In [10]:
import numpy
n = numpy.arange(27)
print("1 Dimensional Array")
n

1 Dimensional Array


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [4]:
type(n)

numpy.ndarray

In [8]:
print("Two Dimensional Array")
n.reshape(3,9)

Two Dimensional Array


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [11]:
print("Thre Dimensional Array")
n.reshape(3,3,3)

Thre Dimensional Array


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [12]:
[[123,453,43],[23,65,77],[67,89,99]]

[[123, 453, 43], [23, 65, 77], [67, 89, 99]]

In [18]:
m=numpy.asarray([[123,453,43],[],[]])
m

array([list([123, 453, 43]), list([]), list([])], dtype=object)

In [19]:
print(m)

[list([123, 453, 43]) list([]) list([])]


In [20]:
m

array([list([123, 453, 43]), list([]), list([])], dtype=object)

In [1]:
import cv2

In [2]:
im_g = cv2.imread("smallgray.png",0)
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [3]:
im_g2 = cv2.imread("smallgray.png",1)
im_g2

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [5]:
print(im_g2)

[[[187 187 187]
  [158 158 158]
  [104 104 104]
  [121 121 121]
  [143 143 143]]

 [[198 198 198]
  [125 125 125]
  [255 255 255]
  [255 255 255]
  [147 147 147]]

 [[209 209 209]
  [134 134 134]
  [255 255 255]
  [ 97  97  97]
  [182 182 182]]]


In [6]:
im_new = cv2.imwrite("newsmallgray.png",im_g)
im_new

True

In [7]:
a=[1,2,3,4]

In [8]:
a[0:1]

[1]

In [9]:
a[2:3]

[3]

In [10]:
a[0:3]

[1, 2, 3]

In [11]:
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [14]:
im_g[0:2]

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147]], dtype=uint8)

In [24]:
im_g[0:2,2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [25]:
im_g.shape

(3, 5)

In [28]:
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [38]:
im_g[0,1]

158

In [39]:
for i in im_g:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [40]:
for i in im_g.T:
    print(i)


[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [41]:
for i in im_g.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [42]:
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [47]:
ims = numpy.hstack((im_g,im_g))
ims

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [48]:
lms2 = numpy.vstack((im_g,im_g))
lms2

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [53]:
lst = numpy.hsplit(lms2,5)
lst

[array([[187],
        [198],
        [209],
        [187],
        [198],
        [209]], dtype=uint8), array([[158],
        [125],
        [134],
        [158],
        [125],
        [134]], dtype=uint8), array([[104],
        [255],
        [255],
        [104],
        [255],
        [255]], dtype=uint8), array([[121],
        [255],
        [ 97],
        [121],
        [255],
        [ 97]], dtype=uint8), array([[143],
        [147],
        [182],
        [143],
        [147],
        [182]], dtype=uint8)]

In [52]:
lstv = numpy.vsplit(lms2,3)
lstv

[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147]], dtype=uint8),
 array([[209, 134, 255,  97, 182],
        [187, 158, 104, 121, 143]], dtype=uint8),
 array([[198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8)]

In [54]:
lstv[0]

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147]], dtype=uint8)

In [58]:
l = lambda x: x**2
l(5)

25

In [59]:
from datetime import datetime as dt

In [60]:
dt.now()

datetime.datetime(2019, 9, 24, 12, 23, 7, 146880)

In [61]:
type(dt.now())

datetime.datetime

In [62]:
dt.now()

datetime.datetime(2019, 9, 24, 13, 6, 36, 357716)

In [63]:
dt.now() < dt(2019, 9, 23, 12)

False

In [64]:
dt.now().year

2019

In [69]:
dt.now().minute

10

In [72]:
dt(dt.now().year,dt.now().month,dt.now().day,8) < dt.now() < dt(dt.now().year,dt.now().month,dt.now().day,16)

True

In [71]:
dt.now().year

2019

In [73]:
dt(dt.now().year,dt.now().month,dt.now().day,8)

datetime.datetime(2019, 9, 24, 8, 0)

In [74]:
dt.now()

datetime.datetime(2019, 9, 24, 13, 19, 19, 676915)

In [75]:
dt(dt.now().year,dt.now().month,dt.now().day,16)

datetime.datetime(2019, 9, 24, 16, 0)